### ISSUE TITLE
Can't use function return value in write context in wp-content\plugins\olympus-google-fonts\includes\customizer\output-css.php on line 51

### ISSUE THREAD

**Issue by diehard27** [DannyCooper/olympus-google-fonts#5]
Environment
Win2008 Server R2 + IIS 7.5
MySQL 5.2
PHP5.4

**Comment by DannyCooper** [comment]
Thanks @diehard27 for finding this bug, it's now been fixed in the latest version - https://wordpress.org/plugins/olympus-google-fonts/
