### ISSUE TITLE
Website Navigation Text Not Changing

### ISSUE THREAD

**Issue by slmlme** [DannyCooper/olympus-google-fonts#6]
Hi there.. I found your plug-in, all seems to work, except the navigation text... any suggestions? i learned that the name of the navigation code i need to change is - .menu li and .nav-menu li    - thanks much.

**Comment by DannyCooper** [comment]
Hi @slmlme,

Could you provide a URL to your website so I can look into this for you?

Thanks

**Comment by slmlme** [comment]
My website is not public right now but I will make public for a few hours
so you can take a look. my website is... sheslivingmylife.com

**Comment by DannyCooper** [comment]
Thank you, I see the problem now and will release a fix shortly.

**Comment by slmlme** [comment]
ok thank you kindly... if you could please let me know that would be great

**Comment by DannyCooper** [comment]
Fixed in 1.0.9

**Comment by slmlme** [comment]
Hi there Danny... just wanted you to know that I deactivated and
reactivayed and forced advanced styles to change my navigation font and it
still has not changed with your recent update.

**Comment by DannyCooper** [comment]
Hi @slmlme,

Your website has this very aggressive CSS that is hard for the plugin to overwrite:

```
body, .post-header h3.post_subtitle, .list-item .post-header h3.post_subtitle, .post-header-single h3.post_subtitle, .ig_cont_single_only_title h3.post_subtitle, #logo_single h1 a, .menu li, .nav-menu li, .container-select-box select, .panel-body .widget_search form input[type='search'], .ig_widget, #instagram-footer, .slidepost__desc h3, .postTime, .wp-caption-text.gallery-caption, .post-header-single h1, .ig_cont_single_only_title h1, .post-header-single .meta_item, .ig_cont_single_only_title .meta_item, .title_about h1, .read-more-list, .title-line, .animsition-loading:after, .textt, .ilgelo_pagination, .wp-caption .wp-caption-text, #commentform textarea, #commentform .submit, .wpcf7 p, div.wpcf7-response-output, #yrecipe-container p, #yrecipe-container li, #yrecipe-container .notes, #yrecipe-container .h-4.strong {
    font-family: 'Merriweather',serif !important;
}
```

**Comment by slmlme** [comment]
Ok totally understand... thank you kindly for all your help... just wanted
to make sure it wasn’t human error.
