### ISSUE TITLE
Unreadable for IE11, Vivaldi latin-ext src link 

### ISSUE THREAD

**Issue by milyl** [DannyCooper/olympus-google-fonts#7]
Hi,
I have problem on a website using this plugin (Polish letters - 'latin-ext'). I'm using Dosis font.
![dosis_without_latin_ext](https://user-images.githubusercontent.com/9466342/34380795-5eb886ca-eb04-11e7-8e90-cd8951375c20.JPG)

Generated `<link rel='stylesheet' id='olympus-google-fonts-css'  href='https://fonts.googleapis.com/css?family=Dosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800&#038;amp&#038;latin-ext,latin&#038;ver=4.9.1' type='text/css' media='all' />` 

from (class-olympus-google-fonts.php line 58)
`wp_enqueue_style( 'olympus-google-fonts',  $url->build() , false );` isn't readable well by IE11 or Vivaldi. Latest Chrome and Firefox doesn't have problems with it.

I tried manually this format:
`wp_enqueue_style('olympus-google-fonts', '//fonts.googleapis.com/css?family=Dosis&subset=latin-ext', false );` and it works better.

Can you fix yours kind of formatting to be cross-browser compatible?

**Comment by DannyCooper** [comment]
Hi Milyl,

I think the problem may be with the browsers. For example, if I use your example URL (`fonts.googleapis.com/css?family=Dosis&subset=latin-ext`) in Chome I get this output:

```
/* latin-ext */
@font-face {
  font-family: 'Dosis';
  font-style: normal;
  font-weight: 400;
  src: local('Dosis Regular'), local('Dosis-Regular'), url(http://fonts.gstatic.com/s/dosis/v7/3isE9muMMOq1K7TQ7HkKvIDGDUGfDkXyfkzVDelzfFk.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Dosis';
  font-style: normal;
  font-weight: 400;
  src: local('Dosis Regular'), local('Dosis-Regular'), url(http://fonts.gstatic.com/s/dosis/v7/oaBFj7Fz9Y9_eW3k9Jd9X6CWcynf_cDxXwCLxiixG1c.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2212, U+2215;
}
```

Whereas in Vivaldi I get this from the exact same URL:

```
@font-face {
  font-family: 'Dosis';
  font-style: normal;
  font-weight: 400;
  src: local('Dosis Regular'), local('Dosis-Regular'), url(http://fonts.gstatic.com/s/dosis/v7/hr7Un5rTZbWMVxBLJvXJaaCWcynf_cDxXwCLxiixG1c.ttf) format('truetype');
}
```

**Comment by milyl** [comment]
Hi DannyCooper,
It seems that IE and Vivaldi has problem to read this long string I mentioned before:
`https://fonts.googleapis.com/css?family=Dosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800%7CDosis%3A200%2C300%2Cregular%2C500%2C600%2C700%2C800&#038;amp&#038;latin-ext,latin&#038;ver=4.9.1`.

I've tested this:
`https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800&amp;subset=latin-ext`
It works in latest Chrome, Firefox, Vivaldi, IE11. It seems this format is proper.

**Comment by DannyCooper** [comment]
Have you tried the latest version (v1.1.0)? It reduces the size of that particular string.

**Comment by milyl** [comment]
Hi DannyCooper,
Issue resolved with new version.
Thank you.

**Comment by DannyCooper** [comment]
Thanks @milyl!
