### ISSUE TITLE
Warning message after update.

### ISSUE THREAD

**Issue by annkathrinjanina** [DannyCooper/olympus-google-fonts#9]
Hi, I updated my plugin today and now i have a warning message. How can I get rid of it?
This is the message.
Warning: Invalid argument supplied for foreach() in /homepages/34/d730268644/htdocs/app730269468/wp-content/plugins/olympus-google-fonts/includes/class-ogf-fonts.php on line 149
Thanks, Anne

**Comment by DannyCooper** [comment]
Hi @annkathrinjanina,

Sorry about that, I am releasing a fix (1.4.5) in a couple of minutes that will fix that.
